### ISSUE TITLE
`$group` gives unexpected results when `_id` is defined as an object

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#3089] opened 2023-07-20 06:16 UTC
### FerretDB version

1.6.0

### Backend

PostgreSQL

### Environment

any

### What did you do?

 ```
db.pampam.insertOne({"_id": 1})
db.pampam.aggregate([ {$group: {"_id": {"foo": "$_id"}}}])
```

See also #3088 for a bit more advanced example.

### What did you expect to see?

```
[ { _id: { foo: 1 } } ]
```

### What did you see instead?

```
[ { _id: { foo: '$_id' } } ]
```

**Comment by AlekSi** [comment] 2023-07-20 06:22
Duplicate of #2165

**Closed by AlekSi** 2023-07-20 06:22 UTC
Labels: code/bug, not ready
