### ISSUE TITLE
ObjectId as an independent column

### ISSUE THREAD

**Issue by stevefan1999-personal** [FerretDB/FerretDB#3011] opened 2023-07-09 13:05 UTC
### What should be done?

I want to have ObjectId as an independent column, so that is the first step towards Citus support.

What is Citus?

> The Citus database is an open source extension to Postgres that gives you all the greatness of Postgres, at any scale—from a single node to a large distributed database cluster. Because Citus is an extension (not a fork) to Postgres, when you use Citus, you are also using Postgres. You can leverage the latest Postgres features, tooling, and ecosystem.
>
> With Citus you get distributed Postgres features like sharding, distributed tables, reference tables, a distributed query engine, columnar storage—and as of Citus 11.0, the ability to query from any node. The Citus combination of parallelism, keeping more data in memory, and higher I/O bandwidth can lead to significant performance improvements for multi-tenant SaaS applications, customer-facing real-time analytics dashboards, and time series workloads.

Right now we are just having everything inside a `_jsonb`, but Citus did not work with that

**Comment by AlekSi** [comment] 2023-07-10 07:25
Duplicate of #226.

Eventually, we will support extracting `_id` and other fields into separate columns.

**Comment by AlekSi** [comment] 2023-07-10 07:26
Duplicate of #226

**Closed by AlekSi** 2023-07-10 07:25 UTC
Labels: code/feature, not ready
