### ISSUE TITLE
Installing on arm/v7

### ISSUE THREAD

**Issue by BoBiene** [FerretDB/FerretDB#3225] opened 2023-08-20 18:05 UTC
### FerretDB version

1.8 (latest)

### Backend

N/A

### Environment

- OS: ubuntu / Dokcer
- Deployment: Dockerfile
- Deployment details: 

### What did you do?

````Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://github.com/FerretDB/FerretDB/releases/latest/download/ferretdb.deb -o /tmp/ferretdb.deb && \
    dpkg -i /tmp/ferretdb.deb

CMD ["ferretdb", "--version"]
````

````bash
docker buildx build -f .\ferret.Dockerfile --platform linux/arm/v7 .
````

### What did you expect to see?

Successfull Docker build

### What did you see instead?

````
[+] Building 51.4s (7/7) FINISHED                                                                                                                                                                 docker:default
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 404B                                                                                                                                                                           0.0s
 => [internal] load build definition from ferret.Dockerfile                                                                                                                                                 0.0s
 => => transferring dockerfile: 660B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                                                            1.4s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                               0.0s
 => [1/3] FROM docker.io/library/ubuntu:latest@sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77                                                                                      0.1s
 => => resolve docker.io/library/ubuntu:latest@sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77                                                                                      0.0s
 => => sha256:c6030a449cb880d2fb07b1f96e5df80e5abf6240abed0917e1a0b949a02b76df 2.31kB / 2.31kB                                                                                                              0.0s
 => => sha256:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77 1.13kB / 1.13kB                                                                                                              0.0s
 => => sha256:c835a4f2a632bc91a2b494e871549f0dd83f2966c780e66435774e77e048ddf0 424B / 424B                                                                                                                  0.0s
 => [2/3] RUN apt-get update && apt-get install -y     curl     && rm -rf /var/lib/apt/lists/*                                                                                                             47.2s
 => ERROR [3/3] RUN curl -fsSL https://github.com/FerretDB/FerretDB/releases/latest/download/ferretdb.deb -o /tmp/ferretdb.deb &&     dpkg -i /tmp/ferretdb.deb                                             2.7s
------
 > [3/3] RUN curl -fsSL https://github.com/FerretDB/FerretDB/releases/latest/download/ferretdb.deb -o /tmp/ferretdb.deb &&     dpkg -i /tmp/ferretdb.deb:
2.635 dpkg: error processing archive /tmp/ferretdb.deb (--install):
2.635  package architecture (amd64) does not match system (armhf)
2.680 Errors were encountered while processing:
2.680  /tmp/ferretdb.deb
------
ferret.Dockerfile:10
--------------------
   9 |     # Lade das FerretDB .deb-Paket herunter und installiere es
  10 | >>> RUN curl -fsSL https://github.com/FerretDB/FerretDB/releases/latest/download/ferretdb.deb -o /tmp/ferretdb.deb && \
  11 | >>>     dpkg -i /tmp/ferretdb.deb
  12 |
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -fsSL https://github.com/FerretDB/FerretDB/releases/latest/download/ferretdb.deb -o /tmp/ferretdb.deb &&     dpkg -i /tmp/ferretdb.deb" did not complete successfully: exit code: 1
````

**Comment by AlekSi** [comment] 2023-08-22 04:52
Currently, our `.deb` packages are built only for amd64. We are going to change that: #2171. In the meantime, you could use our [multi-arch Docker image](https://github.com/FerretDB/FerretDB/pkgs/container/ferretdb) either directly, as a base image, or by extracting a binary from it and adding it to your image.

**Comment by AlekSi** [comment] 2023-08-22 04:52
Duplicate of #2171

**Closed by AlekSi** 2023-08-22 04:52 UTC
Labels: code/bug, not ready
