### ISSUE TITLE
Support C# MongoDB Client Linq query filter

### ISSUE THREAD

**Issue by BoBiene** [FerretDB/FerretDB#3168] opened 2023-08-07 10:00 UTC
### FerretDB version

v1.7.0

### Backend

SQLite

### Environment

- OS: Windows 11
- Deployment: ghcr.io/ferretdb/all-in-one
- Deployment details: Docker Desktop v4.21.1, Docker version 24.0.2, build cb74dfc

### What did you do?

Using a Linq filter with the C# client

### What did you expect to see?

Documents matching the request filter

### What did you see instead?

2023-08-07T09:42:33.482Z    DEBUG   // 172.17.0.1:60614 -> 172.17.0.3:27017         clientconn/conn.go:288  Request message:
2023-08-07 11:42:33 {
2023-08-07 11:42:33   "Checksum": 0,
2023-08-07 11:42:33   "FlagBits": 0,
2023-08-07 11:42:33   "Sections": [
2023-08-07 11:42:33     {
2023-08-07 11:42:33       "Document": {
2023-08-07 11:42:33         "$k": [
2023-08-07 11:42:33           "aggregate",
2023-08-07 11:42:33           "pipeline",
2023-08-07 11:42:33           "cursor",
2023-08-07 11:42:33           "$db"
2023-08-07 11:42:33         ],
2023-08-07 11:42:33         "aggregate": "PlugInConfig",
2023-08-07 11:42:33         "pipeline": [
2023-08-07 11:42:33           {
2023-08-07 11:42:33             "$k": [
2023-08-07 11:42:33               "$match"
2023-08-07 11:42:33             ],
2023-08-07 11:42:33             "$match": {
2023-08-07 11:42:33               "$k": [
2023-08-07 11:42:33                 "PlugInTypeID",
2023-08-07 11:42:33                 "InstanceName",
2023-08-07 11:42:33                 "_id"
2023-08-07 11:42:33               ],
2023-08-07 11:42:33               "PlugInTypeID": 20000,
2023-08-07 11:42:33               "InstanceName": "Test",
2023-08-07 11:42:33               "_id": {
2023-08-07 11:42:33                 "$k": [
2023-08-07 11:42:33                   "$ne"
2023-08-07 11:42:33                 ],
2023-08-07 11:42:33                 "$ne": "2308070941-162715339-D097E532-00009E25"
2023-08-07 11:42:33               }
2023-08-07 11:42:33             }
2023-08-07 11:42:33           },
2023-08-07 11:42:33           {
2023-08-07 11:42:33             "$k": [
2023-08-07 11:42:33               "$limit"
2023-08-07 11:42:33             ],
2023-08-07 11:42:33             "$limit": 1
2023-08-07 11:42:33           }
2023-08-07 11:42:33         ],
2023-08-07 11:42:33         "cursor": {
2023-08-07 11:42:33           "$k": []
2023-08-07 11:42:33         },
2023-08-07 11:42:33         "$db": "ApplicationConfig"
2023-08-07 11:42:33       },
2023-08-07 11:42:33       "Kind": 0
2023-08-07 11:42:33     }
2023-08-07 11:42:33   ]
2023-08-07 11:42:33 }
2023-08-07 11:42:33 
2023-08-07 11:42:33 
2023-08-07 11:42:33 
2023-08-07 11:42:33 2023-08-07T09:42:33.482Z    WARN    // 172.17.0.1:60614 -> 172.17.0.3:27017         clientconn/conn.go:598  Response header: length:   134, id:    9, response_to:  157, opcode: OP_MSG
2023-08-07 11:42:33 github.com/FerretDB/FerretDB/internal/clientconn.(*conn).logResponse
2023-08-07 11:42:33     /src/internal/clientconn/conn.go:598
2023-08-07 11:42:33 github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
2023-08-07 11:42:33     /src/internal/clientconn/conn.go:311
2023-08-07 11:42:33 github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
2023-08-07 11:42:33     /src/internal/clientconn/listener.go:321
2023-08-07 11:42:33 2023-08-07T09:42:33.482Z    WARN    // 172.17.0.1:60614 -> 172.17.0.3:27017         clientconn/conn.go:599  Response message:
2023-08-07 11:42:33 {
2023-08-07 11:42:33   "Checksum": 0,
2023-08-07 11:42:33   "FlagBits": 0,
2023-08-07 11:42:33   "Sections": [
2023-08-07 11:42:33     {
2023-08-07 11:42:33       "Document": {
2023-08-07 11:42:33         "$k": [
2023-08-07 11:42:33           "ok",
2023-08-07 11:42:33           "errmsg",
2023-08-07 11:42:33           "code",
2023-08-07 11:42:33           "codeName"
2023-08-07 11:42:33         ],
2023-08-07 11:42:33         "ok": {
2023-08-07 11:42:33           "$f": 0
2023-08-07 11:42:33         },
2023-08-07 11:42:33         "errmsg": "I'm a stub, not a real handler for aggregate",
2023-08-07 11:42:33         "code": 238,
2023-08-07 11:42:33         "codeName": "NotImplemented"
2023-08-07 11:42:33       },
2023-08-07 11:42:33       "Kind": 0
2023-08-07 11:42:33     }
2023-08-07 11:42:33   ]
2023-08-07 11:42:33 }
2023-08-07 11:42:33

**Comment by AlekSi** [comment] 2023-08-16 05:19
`aggregate` command is already supported by the PostgreSQL backend. We have an existing issue for making it available to the SQLite backend.

**Comment by AlekSi** [comment] 2023-08-16 05:19
Duplicate of #3148

**Closed by AlekSi** 2023-08-16 05:19 UTC
Labels: code/bug, not ready
