### ISSUE TITLE
the problem with BatchSize is in registry.TestOpts{} when using as embedded

### ISSUE THREAD

**Issue by Moriartii** [FerretDB/FerretDB#4249] opened 2024-04-19 11:16 UTC
### FerretDB version

1.21.0

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.04 x86_64

### What did you do?

I started app from this example https://github.com/FerretDB/embedded-example and got panic, because  **registry.TestOpts.BatchSize** is 0 (zero) inside **ferretdb.New(config *Config) (*FerretDB, error)**:

2024-04-19T13:56:00.129+0300    DPANIC  // 127.0.0.1:45940 -> 127.0.0.1:27017   clientconn/conn.go:170  batch-size should be greater or equal to 1
(err = <nil>)

github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func3
        /home/nikolay/ferretd/vendor/github.com/FerretDB/FerretDB/internal/clientconn/conn.go:170
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:770
github.com/FerretDB/FerretDB/internal/backends/postgresql.(*collection).InsertAll.func1
        /home/nikolay/ferretd/vendor/github.com/FerretDB/FerretDB/internal/backends/postgresql/collection.go:139
github.com/jackc/pgx/v5.beginFuncExec
        /home/nikolay/ferretd/vendor/github.com/jackc/pgx/v5/tx.go:425
github.com/jackc/pgx/v5.BeginFunc
        /home/nikolay/ferretd/vendor/github.com/jackc/pgx/v5/tx.go:394
github.com/FerretDB/FerretDB/internal/backends/postgresql/metadata/pool.InTransaction

```
func New(config *Config) (*FerretDB, error) {
	version.Get().Package = "embedded"

	if config.Listener.TCP == "" &&
		config.Listener.Unix == "" &&
		config.Listener.TLS == "" {
		return nil, errors.New("Listener TCP, Unix and TLS are empty")
	}

	sp, err := state.NewProvider("")
	if err != nil {
		return nil, fmt.Errorf("failed to construct handler: %s", err)
	}

	// Telemetry reporter is not created or running anyway,
	// but disable telemetry explicitly to disable confusing startupWarnings.
	err = sp.Update(func(s *state.State) {
		s.DisableTelemetry()
		s.TelemetryLocked = true
	})
	if err != nil {
		return nil, fmt.Errorf("failed to construct handler: %s", err)
	}

	metrics := connmetrics.NewListenerMetrics()

	log := config.Logger
	if log == nil {
		log = getGlobalLogger()
	} else {
		log = logging.WithHooks(log)
	}

	h, closeBackend, err := registry.NewHandler(config.Handler, &registry.NewHandlerOpts{
		Logger:        log,
		ConnMetrics:   metrics.ConnMetrics,
		StateProvider: sp,
		TCPHost:       config.Listener.TCP,

		PostgreSQLURL: config.PostgreSQLURL,

		SQLiteURL: config.SQLiteURL,

		TestOpts: registry.TestOpts{
			CappedCleanupPercentage: 10, // handler expects it to be a non-zero value
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to construct handler: %s", err)
	}

	l := clientconn.NewListener(&clientconn.NewListenerOpts{
		TCP:  config.Listener.TCP,
		Unix: config.Listener.Unix,

		TLS:         config.Listener.TLS,
		TLSCertFile: config.Listener.TLSCertFile,
		TLSKeyFile:  config.Listener.TLSKeyFile,
		TLSCAFile:   config.Listener.TLSCAFile,

		Mode:    clientconn.NormalMode,
		Metrics: metrics,
		Handler: h,
		Logger:  log,
	})

	return &FerretDB{
		config:       config,
		closeBackend: closeBackend,
		l:            l,
	}, nil
}


### What did you expect to see?

normal example result

### What did you see instead?

panic

**Comment by AlekSi** [comment] 2024-04-22 07:13
Duplicate of #4235

**Closed by AlekSi** 2024-04-22 07:13 UTC
Labels: code/bug, not ready
