### ISSUE TITLE
Implement `size` field for capped collections

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2813] opened 2023-06-07 15:46 UTC
### What should be done?

Depends on #75.

* https://www.mongodb.com/docs/manual/reference/command/create/#command-fields

> integer | Optional. Specify a maximum size in bytes for a capped collection. Once a capped collection reaches its maximum size, MongoDB removes the older documents to make space for the new documents. The size field is required for capped collections and ignored for other collections.

**Comment by AlekSi** [comment] 2023-06-08 18:24
Let's use #75 for that

**Comment by AlekSi** [comment] 2023-06-08 18:25
Duplicate of #75

**Closed by AlekSi** 2023-06-08 18:24 UTC
Labels: code/feature, not ready
