### ISSUE TITLE
Support tailable cursors in `find`

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2963] opened 2023-07-04 06:25 UTC
### What should be done?

https://www.mongodb.com/docs/manual/core/tailable-cursors/

Tailable cursors do not close when it exhausted results, the cursor is kept open waiting for more documents to be added. It's available for find cursor. Not available for aggregate cursor.

issue number added in PR https://github.com/FerretDB/FerretDB/pull/2953

### Where?

https://github.com/FerretDB/FerretDB/blob/cbd9e06a3361e0b88ee81d4323f93e62c3635106/internal/handlers/pg/msg_find.go#L161

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;

**Comment by AlekSi** [comment] 2023-07-10 14:01
Duplicate of #2283

**Closed by AlekSi** 2023-07-10 14:01 UTC
Labels: code/enhancement, not ready
