### ISSUE TITLE
Calling `explain` on non-existent collection returns an error

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#2296] opened 2023-03-27 18:22 UTC
### Versions

0.9.4

### What did you do?

```
db.nonexistent.explain().find()
```

### What did you expect to see?

Some information from query planner (run FerretDB with proxy mode to see an example)

### What did you see instead?

```
 [transactions.go:84 pgdb.(*Pool).InTransaction] [query.go:58 pgdb.Explain] [database_metadata.go:178 pgdb.(*metadataStorage).getTableName] collection/table does not exist
```

### Environment

```markdown
- OS: macOS
- Architecture: arm
- Version: 9.4
- Deployment: dev
```

**Comment by AlekSi** [comment] 2023-08-22 13:22
Duplicate of #2280

**Closed by AlekSi** 2023-08-22 13:22 UTC
Labels: code/bug, not ready
