### ISSUE TITLE
SQLite Empty Aggregate returns "I'm a stub, not a real handler for aggregate"

### ISSUE THREAD

**Issue by BoBiene** [FerretDB/FerretDB#3273] opened 2023-08-29 12:41 UTC
### FerretDB version

1.9

### Backend

SQLite

### Environment

- OS: Linux
- Deployment: ghcr.io/ferretdb/ferretdb:1.9.0
- Deployment details: Docker on Ubuntu

### What did you do?

Query with empty aggregate 

### What did you expect to see?

All elements from the collection

### What did you see instead?

"I'm a stub, not a real handler for aggregate"

**Comment by AlekSi** [comment] 2023-08-30 05:14
It will be available in v1.10.0.

**Comment by AlekSi** [comment] 2023-08-30 05:14
Duplicate of #3148

**Closed by AlekSi** 2023-08-30 05:14 UTC
Labels: code/bug, not ready
