### ISSUE TITLE
Can't connect by C# MongoDB Driver

### ISSUE THREAD

**Issue by dma198** [FerretDB/FerretDB#2516] opened 2023-04-26 09:45 UTC
There are two issues.

First, FerretDB should handle that problem more gracefully, not `DPanic`. Not sure if we will be able to add an integration test for that using the Go driver, so let's reproduce that problem with https://github.com/FerretDB/dotnet-example before fixing it.

Second, for some reason, that driver tries to use a deprecated protocol we don't implement. So we probably should return some fields in the initial response to switch protocol.

---

### Versions

latest docker

### What did you do?

Just tried to connect in C#.
Connection from Compass and Java JDBC (DataGrip) works.

### How can we reproduce it?

Just try to open connection by latest MongoDB client in C#

### What did you expect to see?

Normal connection as to real MongoDB, if something is not implemented yet (what can be in just opening connection?) then return error for requested connection and continue to work.

### What did you see instead?

Docker container went to crashing cycle with messages below and not possible to connect anymore by anything...

<details><summary>Log</summary>

```
2023-04-26T09:33:37.424Z	ERROR	// 192.168.18.90:58388 -> 172.17.0.5:27017 	clientconn/conn.go:477	Handler error for unhandled response opcode{error 26 0  NotImplemented (238): CmdQuery: unhandled command "getLastError"} {opcode 25 0  OP_REPLY}
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).route
	/src/internal/clientconn/conn.go:477
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	/src/internal/clientconn/conn.go:292
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
	/src/internal/clientconn/listener.go:307
2023-04-26T09:33:37.425Z	DEBUG	// 192.168.18.90:58388 -> 172.17.0.5:27017 	clientconn/conn.go:555	Response header: length:     0, id:    0, response_to:    0, opcode: OP_REPLY
2023-04-26T09:33:37.425Z	DEBUG	// 192.168.18.90:58388 -> 172.17.0.5:27017 	clientconn/conn.go:556	Response message:
<nil>



2023-04-26T09:33:37.425Z	DPANIC	// 192.168.18.90:58388 -> 172.17.0.5:27017 	clientconn/conn.go:162	runtime error: invalid memory address or nil pointer dereference
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func3
	/src/internal/clientconn/conn.go:162
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:890
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:837
github.com/FerretDB/FerretDB/internal/wire.(*OpReply).MarshalBinary
	/src/internal/wire/op_reply.go:92
github.com/FerretDB/FerretDB/internal/wire.WriteMessage
	/src/internal/wire/msg_body.go:104
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	/src/internal/clientconn/conn.go:352
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
	/src/internal/clientconn/listener.go:307
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
(err = <nil>)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc647cf]

goroutine 83 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc000498750, {0x19ecd9a?, 0x42?, 0xc0001c82c0?})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0xa8
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000498750, {0x0, 0x0, 0x0})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x586
go.uber.org/zap.(*SugaredLogger).log(0xc0004a0058, 0x3, {0x17029d4, 0xd}, {0xc0004c8f90, 0x2, 0x2}, {0x0, 0x0, 0x0})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/sugar.go:295 +0x13b
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	/cache/gomodcache/go.uber.org/zap@v1.24.0/sugar.go:184
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func3()
	/src/internal/clientconn/conn.go:162 +0x195
panic({0x15980c0, 0x205e0e0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/FerretDB/FerretDB/internal/wire.(*OpReply).MarshalBinary(0x0)
	/src/internal/wire/op_reply.go:92 +0x8f
github.com/FerretDB/FerretDB/internal/wire.WriteMessage(0xc0004aa180?, 0xc00062a000, {0x18ea7c0, 0x0})
	/src/internal/wire/msg_body.go:104 +0xaf
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc0004aa180, {0x18e9ba8, 0xc000220840})
	/src/internal/clientconn/conn.go:352 +0x2945
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1()
	/src/internal/clientconn/listener.go:307 +0xd05
created by github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop
	/src/internal/clientconn/listener.go:267 +0x714
```

</details>

### Environment

```markdown
- OS: Ubuntu 22.04
- Architecture: x64
- Version: latest docker
- Deployment: Docker
- Deployment details: 20.10.21
```

**Comment by b1ron** [comment] 2023-05-11 13:34
This seems to happen when there's no `connectionId` present in the `isMaster` response. The driver still seems to execute a getLastError command as part of the server handshake.

We currently do not return a connection ID in the [response](https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/msg_ismaster.go#L39).

**Comment by AlekSi** [comment] 2023-05-12 06:04
@dma198 Please try with [that](https://github.com/FerretDB/FerretDB/pkgs/container/ferretdb-dev/92631459?tag=main) or [that](https://github.com/FerretDB/FerretDB/pkgs/container/all-in-one/92628653?tag=main) image.

**Comment by stevefan1999-personal** [comment] 2023-07-09 13:38
@AlekSi The problem still persists on the latest version of MongoDB.Driver
```
<PackageReference Include="MongoDB.Driver" Version="2.20.0" />
```

```
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func3
	/src/internal/clientconn/conn.go:164
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:890
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	/src/internal/clientconn/conn.go:370
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
	/src/internal/clientconn/listener.go:321
panic: no response to send to client [recovered]
	panic: no response to send to client
(err = <nil>)

goroutine 115 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc00071cea0, {0x1c1a8a9?, 0x42?, 0xc0000dc000?})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0xa8
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00071cea0, {0x0, 0x0, 0x0})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x586
go.uber.org/zap.(*SugaredLogger).log(0xc000290098, 0x3, {0x193dada, 0xd}, {0xc0003e5188, 0x2, 0x2}, {0x0, 0x0, 0x0})
	/cache/gomodcache/go.uber.org/zap@v1.24.0/sugar.go:295 +0x13b
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	/cache/gomodcache/go.uber.org/zap@v1.24.0/sugar.go:184
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func3()
	/src/internal/clientconn/conn.go:164 +0x195
panic({0x17a9000, 0x1afdc20})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc0005d0000, {0x1b0b7a8, 0xc000568f60})
	/src/internal/clientconn/conn.go:370 +0x3698
github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1()
	/src/internal/clientconn/listener.go:321 +0xd8b
created by github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop
	/src/internal/clientconn/listener.go:272 +0x6ca

```

```
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb-dev:main
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: postgres://ferretdb/ferretdb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
```

**Comment by AlekSi** [comment] 2023-07-10 12:14
@stevefan1999-personal Please check with that image: https://github.com/ferretdb/FerretDB/pkgs/container/all-in-one/108222649?tag=pr-sasl-opquery

**Comment by stevefan1999-personal** [comment] 2023-07-20 17:29
> @stevefan1999-personal after some digging I found https://jira.mongodb.org/browse/CSHARP-3516. It's possible to set the stable API field to force the handshake to use OP_MSG and avoid the behavior seen above.
> 
> You could also use the normal `ghcr.io/ferretdb/ferretdb-dev:main` image and set the below in the client:
> 
> ```c#
> 
> var settings = MongoClientSettings.FromConnectionString(connectionUri);
>  
> // Set the ServerApi field of the settings object to Stable API version 1
> settings.ServerApi = new ServerApi(ServerApiVersion.V1);
>  
> // Create a new client and connect to the server
> var client = new MongoClient(settings);
> ```
> 
> Let us know if this resolves the issue. I have tested it and it works. But we are working on a proper fix so that you do not have to tweak these settings in the client.
> 
> 

This does look reasonable. This kinda breaks DI use. I will be checking it few days soon

**Comment by AlekSi** [comment] 2023-07-20 18:21
We are going to fix it in the next release anyway; no changes in code will be needed if the driver version is recent enough.

**Comment by stevefan1999-personal** [comment] 2023-07-22 15:55
@b1ron Can confirm it works:

```cs
using Cocona;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using MongoAsyncEnumerableAdapter;
using MongoDB.Bson;
using MongoDB.Driver;

var builder = CoconaApp.CreateBuilder();

builder.Services.AddSingleton(_ =>
{
    var settings = MongoClientSettings.FromConnectionString("mongodb://postgres:5d9c-2d95-4169-9ae@localhost:27017/?authMechanism=PLAIN");
    settings.ServerApi = new (ServerApiVersion.V1);
    return settings;
});

builder.Services.AddSingleton<IMongoClient>(provider =>
    new MongoClient(provider.GetRequiredService<MongoClientSettings>())
);

builder.Logging.AddConsole();

var app = builder.Build();

app.AddCommand(async (ILogger<Program> logger, IMongoClient mongoClient) =>
{
    await foreach (var name in (await mongoClient.ListDatabaseNamesAsync()).ToAsyncEnumerable())
    {
        logger.LogInformation("Database name: {}", name);
    }

    var database = mongoClient.GetDatabase("ferretdb");
    await database.DropCollectionAsync("root");
    var collection = database.GetCollection<Root>("root");
    await collection.InsertOneAsync(new("John Doe"));
    var find = collection.FindAsync(_ => true);
    await foreach (var rec in find.ToAsyncEnumerable())
    {
        logger.LogInformation("Record: {}", rec);
    }
  
    logger.LogInformation("Done");
});

app.Run();

public record Root(string Name)
{
    public ObjectId Id { get; set; }
}
```

**Comment by AlekSi** [comment] 2023-07-24 12:28
FerretDB PR merged, we need to update dance tests

**Comment by AlekSi** [comment] 2023-07-25 08:35
@stevefan1999-personal that should be fixed in v1.7.0. In the meantime, you could test with [that](https://github.com/FerretDB/FerretDB/pkgs/container/ferretdb-dev/112203433?tag=main) or [that](https://github.com/FerretDB/FerretDB/pkgs/container/all-in-one/112200529?tag=main) Docker images.

**Closed by AlekSi** 2023-07-25 08:35 UTC
Labels: code/bug

**Comment by stevefan1999-personal** [comment] 2023-07-26 06:07
@AlekSi There is a long way to go, in fact, the insert operation is still seemingly unsupported. There is an unknown `apiVersion` field for some reason and threw an exception. But let's make a new issue for that and keep this issue closed instead.

**Comment by stevefan1999-personal** [comment] 2023-07-26 06:07
@AlekSi There is a long way to go, in fact, the insert operation is still seemingly unsupported. There is an unknown `apiVersion` field for some reason and threw an exception. But let's make a new issue for that and keep this issue closed instead.

**Comment by AlekSi** [comment] 2023-07-26 09:25
@stevefan1999-personal Please do. `insert` should work, of course. So that's probably something specific during the initial handshake that triggers that problem. [Debug logs](https://docs.ferretdb.io/configuration/logging/) should help.

**Comment by b1ron** [comment] 2023-07-27 19:34
@stevefan1999-personal as we have introduced a fix there's no longer a need to set the stable API in the client as outlined in this [comment](https://github.com/FerretDB/FerretDB/issues/2516#issuecomment-1629399401).

The issue you're encountering is caused by how we parse fields due to setting `ServerApiVersion.V1`.

Please revert those changes in the client and there should be no issue.

Let us know.
