### ISSUE TITLE
Add negative case authentication tests

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#1921] opened 2023-02-06 05:29 UTC
### What should be done?

In #1568, the test setup was reworked. The positive case authentication is tested within integration tests.

This issue is about adding negative cases of authentication in integration test.

The negative test case would require creating a listener and a client specific TSL parameters.

We already know that driver does attempts multiple reconnect until timeout if 1) TCP clients attempts to connect to TSL or 2) TSL client attempts to connect to TSL. So those won't be tested. 
### Where?

See positive case testing.
https://github.com/FerretDB/FerretDB/blame/01d152e3c220f334a5208763c361e7dc7c8ea220/integration/embedded_test.go#L41

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment] 2023-05-18 11:34
Duplicate of #1877

**Closed by AlekSi** 2023-05-18 11:34 UTC
Labels: code/chore, not ready
