### ISSUE TITLE
Fix parallel collection creation in SQLite

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#2923] opened 2023-06-27 18:55 UTC
### What should be done?

After enabling cursors in #2864 the `TestCollectionName` test started to fail because of database lock (`SQLITE_BUSY`).

### Where?

TBD

### Definition of Done

- all handlers updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?
TBD

**Comment by AlekSi** [comment] 2023-06-28 18:38
Duplicate of #2747

**Closed by AlekSi** 2023-06-28 18:38 UTC
Labels: code/chore, not ready
