### ISSUE TITLE
Return a Location40602 error when `$collStats` is not the first stage in the pipeline

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2763] opened 2023-06-01 14:12 UTC
### FerretDB version

commit.txt: https://github.com/FerretDB/FerretDB/commit/4a69d977535fc0a67e523095b4ddb22cf26d9079
version.txt: v1.2.0

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.10 x86_64
- Deployment: v1.2.0
- Deployment details: 23.0.3

### What did you do?

See repro #2764

### What did you expect to see?

```
	"errmsg" : "$collStats is only valid as the first stage in a pipeline",
	"code" : 40602,
	"codeName" : "Location40602"
```

### What did you see instead?

```
	"errmsg" : "$collStats is only valid as the first stage in a pipeline",
	"code" : 40415,
	"codeName" : "Location40415"
```

**Comment by chilagrow** [comment] 2023-08-14 08:01
Duplicate of https://github.com/FerretDB/FerretDB/issues/2349.

**Closed by chilagrow** 2023-08-14 08:01 UTC
Labels: code/bug, not ready

**Comment by AlekSi** [comment] 2023-08-22 10:18
Duplicate of #2349
