### ISSUE TITLE
Allow `batchSize` to be any numeric type

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2720] opened 2023-05-27 01:35 UTC
### FerretDB version

commit.txt: 43a40249aef7a8abef0eb956a6263111051ac5c9
package.txt: docker-local
branch.txt: main
version.txt: v1.2.0-13-g43a40249-dirty

### Backend

PostgreSQL

### Environment

- OS: Ubuntu 22.10 x86_64
- Deployment: v1.2.0-13-g43a40249-dirty
- Deployment details: Deployment details: 23.0.3

### What did you do?

Some options are loosely typed in the `mongo` shell but are then parsed according to type constraints in MongoDB. All numeric types are stored as doubles, and because of this I suspect they will silently fail a lot of cursor related jstests. We should probably handle this.

```sh
mongo --quiet --eval 'db.foo.find({}).batchSize(1);'
```

### What did you expect to see?

That the `batchSize` was parsed to an int32.

### What did you see instead?

```
Error: error: {
	"ok" : 0,
	"errmsg" : "BSON field 'batchSize' is the wrong type 'double', expected type 'int'",
	"code" : 14,
	"codeName" : "TypeMismatch"
}
```

See also:

```js
// response from MongoDB in legacy shell
---
> db.foo.find({}).batchSize("a")
Error: error: {
	"ok" : 0,
	"errmsg" : "BSON field 'FindCommandRequest.batchSize' is the wrong type 'string', expected types '[long, int, decimal, double']",
	"code" : 14,
	"codeName" : "TypeMismatch"
}
```

**Comment by AlekSi** [comment] 2023-05-29 09:20
Duplicate of #2005

**Closed by AlekSi** 2023-05-29 09:20 UTC
Labels: code/bug, not ready
