### ISSUE TITLE
Support operators in query projection

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#3075] opened 2023-07-19 07:39 UTC
### What should be done?

Operator support was added in aggregation projection, we should do the same for query projection.

See issue link added by PR https://github.com/FerretDB/FerretDB/pull/3063

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/projection.go

### Definition of Done

- integration/compatibility tests added/updated;
- spot refactorings done;

**Comment by AlekSi** [comment] 2023-07-19 07:41
@chilagrow I'm pretty sure that's #835. Please use that issue.

**Comment by AlekSi** [comment] 2023-07-19 07:41
Duplicate of #835

**Comment by chilagrow** [comment] 2023-07-19 07:42
Ouch thanks, my search skill is pretty bad :see_no_evil:

**Closed by AlekSi** 2023-07-19 07:41 UTC
Labels: code/chore, not ready
