### ISSUE TITLE
Update can violate immutable property of `_id`

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#3619] opened 2023-10-19 13:35 UTC
### FerretDB version

version: v1.12.1-46-g384c284f

It's technically not mutating `_id` (or maybe it is) but somehow seems to modify a completely different document than the one we matched. 

### Backend

Any

### Environment

- OS:
- Deployment:
- Deployment details:

### What did you do?

See repro in #3618.

### What did you expect to see?

```
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 0,
        "nModified" : 0,
        "writeError" : {
                "code" : 66,
                "errmsg" : "After applying the update, the (immutable) field '_id' was found to have been altered to _id: 3.0"
        }
})
```

### What did you see instead?

It modified document A or document with `_id: 3` value.

**Comment by chilagrow** [comment] 2023-10-20 02:01
Looks like same as https://github.com/FerretDB/FerretDB/issues/3017

**Comment by AlekSi** [comment] 2024-05-30 11:59
Duplicate of #3017

**Closed** 2024-05-30 11:58 UTC
Labels: code/bug, not ready
