### ISSUE TITLE
Implement `$expr` operator

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2722] opened 2023-05-29 07:04 UTC
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/query/expr/#mongodb-query-op.-expr

`$match` aggregation stage does not accept raw aggregation operators but it supports `$expr` operator
example: `{ $match: { $expr: { <aggregation expression> } } }` from [manual](https://www.mongodb.com/docs/manual/reference/operator/aggregation/match/#restrictions)
https://github.com/FerretDB/FerretDB/blob/0992e5f8a410e59041a62a12f666eacf6f3bd27b/internal/handlers/common/aggregations/stages/match.go#L50
### Where?

https://github.com/FerretDB/FerretDB/blob/0992e5f8a410e59041a62a12f666eacf6f3bd27b/internal/handlers/common/filter.go#L38

### Definition of Done

- all handlers updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;

**Comment by AlekSi** [comment] 2023-05-29 08:39
Duplicate of #414

**Closed by AlekSi** 2023-05-29 08:39 UTC
Labels: code/chore, not ready
