### ISSUE TITLE
Implement validation for `dropIndexes` command

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#3342] opened 2023-09-12 06:47 UTC
### What should be done?

This issue is similar to #3320. Currently, we don't have much validation for `dropIndexes`. Because of this, some tests are marked failed. 

### Where?

See TODOs in the code.

### Definition of Done

- validation implemented;
- integration/compatibility tests added/updated;
- spot refactorings done.

**Comment by AlekSi** [comment] 2023-09-12 08:30
Duplicate of #3320

**Closed by AlekSi** 2023-09-12 08:30 UTC
Labels: code/enhancement, not ready

**Comment by rumyantseva** [comment] 2023-09-12 08:31
@AlekSi let's keep them separate to have smaller PRs?
