### ISSUE TITLE
Compatibility with WeKan

### ISSUE THREAD

**Issue by yu-re-ka** [FerretDB/FerretDB#2501] opened 2023-04-21 14:47 UTC
### What should be done?

https://github.com/wekan/wekan

Currently fails:

```
errorClass [Error]: [An error occurred when creating an index for collection "users: Index option "sparse" is not implemented yet]
    at Collection.createIndex (packages/mongo/collection.js:801:15)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1777:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
    at packages/accounts-base/server_main.js:7:12
```

**Comment by yu-re-ka** [comment] 2023-04-21 14:47
Similar to #2414

**Comment by b1ron** [comment] 2023-04-21 15:04
Added it #1752.

Thanks!

**Comment by AlekSi** [comment] 2023-04-21 19:14
Yeah, let's track that in #1752 and #2448.

Duplicate of #1752

**Comment by AlekSi** [comment] 2023-04-21 19:15
Duplicate of #1752

**Closed by AlekSi** 2023-04-21 19:14 UTC
Labels: code/enhancement
