### ISSUE TITLE
Implement `$avg` group operator

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2126] opened 2023-03-06 07:14 UTC
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/aggregation/avg/#mongodb-group-grp.-avg

**Comment by b1ron** [comment] 2024-04-02 07:02
Duplicate of #2891.

**Closed by b1ron** 2024-04-02 07:02 UTC
Labels: code/feature, not ready, area/aggregations

**Comment by AlekSi** [comment] 2024-04-02 07:16
Duplicate of #2891
