### ISSUE TITLE
Support Change Streams

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1829] opened 2023-01-18 21:41 UTC
### What should be done?

* https://www.mongodb.com/docs/manual/changeStreams/
* https://www.mongodb.com/docs/manual/reference/change-events/

**Comment by AlekSi** [comment] 2023-02-09 12:02
#175

**Comment by AlekSi** [comment] 2023-02-09 12:02
Duplicate of #175

**Closed by AlekSi** 2023-02-09 12:02 UTC
Labels: code/feature
