### ISSUE TITLE
`collStats` and aggregation `$collStats` stage count is not correct

### ISSUE THREAD

**Issue by chilagrow** [FerretDB/FerretDB#2369] opened 2023-04-05 08:29 UTC
### Versions

1.0.0

### What did you do?

Used collection from https://github.com/mcampo2/mongodb-sample-databases/tree/6d512bbb786be9cc12438627488ae581ab5a7d92/sample_geospatial
```
mongoimport --db geospatial --collection geospatial sample_geospatial/shipwrecks.json
```
And count field of collStats both in command and aggregation is not correct.

### What did you expect to see?

collStats
```
geospatial> db.runCommand({collStats:"geospatial", scale:1000})
{
  ns: 'geospatial.geospatial',                                      
  count: 8081,                                                                                                                                                                                             
  size: 15785,                                                               
  storageSize: 15081,                                                                        
  totalIndexSize: 663,                                                                    
  totalSize: 15785,                                                                                                
  scaleFactor: 1000,                                                                                                                                                                                       
  ok: 1  
} 
```

aggregation `$collStats`
```
db.geospatial.aggregate([{$collStats:{count:{}}}])        
[                                                                                            
  {                                                                                                  
    ns: 'geospatial.geospatial',                                                          
    host: 'alma',                                                                                 
    localTime: '2023-04-05T08:22:14Z',                                     
    count: 8081                                                                      
  }                                                                         
]            
```

What it should be `11095`
```
geospatial> db.geospatial.find().count()                         
11095 
geospatial> db.geospatial.countDocuments()
11095
geospatial> db.geospatial.estimatedDocumentCount()
11095

```

### What did you see instead?

Expect count to be `11095`

### Environment

```markdown
- OS:
- Architecture:
- Version:
- Deployment:
- Deployment details:
```

**Comment by chilagrow** [comment] 2023-04-05 09:12
Closing because it cannot be reproduce and works on other environment.

**Comment by b1ron** [comment] 2023-04-05 09:31
I can confirm that this is an issue.

commit.txt: 37f0565eb9fef3ca1008631fd9617e6bdee29c0f
branch.txt: main
version.txt: v1.0.0-6-g37f0565e

See below:

```
mongoimport --db geospatial --collection geospatial dumps/mongodb-sample-databases/sample_geospatial/shipwrecks.json
2023-04-05T11:24:39.553+0200	11095 document(s) imported successfully. 0 document(s) failed to import.
```

```
> use geospatial
switched to db geospatial
> db.geospatial.count()
11095
> db.geospatial.aggregate([{$collStats: {count: {}}}]).pretty()
{
	"ns" : "geospatial.geospatial",
	"host" : "byron-ThinkCentre-M910q",
	"localTime" : "2023-04-05T09:29:44Z",
	"count" : 11134
}
> db.runCommand({collStats: "geospatial"}).count
11134
```

**Comment by rumyantseva** [comment] 2023-04-05 11:03
One more thing to check int the scope of this RP is if `collStats` command has the same problem:

```
db.runCommand({
  collStats: "geospatial",
  scale: 1
})
```

**Comment by chilagrow** [comment] 2023-04-06 00:35
> One more thing to check in the scope of this issue is if `collStats` command has the same problem:
> 
> ```
> db.runCommand({
>   collStats: "geospatial",
>   scale: 1
> })
> ```

Yeah collStats also have the same problem, see the output in the description

**Comment by AlekSi** [comment] 2023-09-29 16:27
Duplicate of #2447

**Comment by AlekSi** [comment] 2023-09-29 16:27
(we have too many similar issues already)

**Closed by AlekSi** 2023-09-29 16:27 UTC
Labels: code/bug, not ready

**Comment by chilagrow** [comment] 2023-10-16 08:01
It reports correctly now.

```
geospatial>  db.runCommand({collStats:"geospatial", scale:1000})
{
  ns: 'geospatial.geospatial',
  size: Long("15081"),
  count: Long("11095"),
  avgObjSize: Long("1359"),
  storageSize: Long("15081"),
  nindexes: Long("1"),
  totalIndexSize: Long("663"),
  totalSize: Long("15745"),
  scaleFactor: 1000,
  capped: false,
  ok: 1
}
geospatial> db.geospatial.aggregate([{$collStats:{count:{}}}])  
[
  {
    ns: 'geospatial.geospatial',
    host: 'alma',
    localTime: '2023-10-16T08:00:07Z',
    count: Long("11095")
  }
]
geospatial> db.geospatial.find().count()
11095
geospatial> db.geospatial.countDocuments()
11095
geospatial> db.geospatial.estimatedDocumentCount()
11095
```
