### ISSUE TITLE
Merge `fuzztool` into `envtool`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2547] opened 2023-05-02 12:28 UTC
### What should be done?

Let's move the existing `fuzztool` implementation to `envtool fuzz corpus <src> <dst>` subcommand.

It probably should be in a separate file, not `envtool.go`.

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/cmd/fuzztool
* https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

- code moved;
- Taskfile updated to use new command;
- CI configuration updated to use new command.

**Comment by Aditya1404Sal** [comment] 2023-05-13 09:03
Hey I'd like to work on this issue
Please assign it to me.

**Comment by rumyantseva** [comment] 2023-05-15 10:34
@Aditya1404Sal thank you! The issue is assigned. If there are any questions, please feel free to ask them here or on Slack.

**Comment by Aditya1404Sal** [comment] 2023-05-15 18:11
I've successfully set up this codebase locally, and I'm in the midst of resolving this issue
So far , i have moved the code to a new file in the cmd/envtool directory & i have updated the appropriate taskfile commands by changing their directory location from cmd/fuzztool to cmd/envtool corpus <src><dst>
Similarly I've changed the CL config script fuzz corpus to it's updated directory location. 
Am i going on the right direction or are there any changes to be made ? 
And do i send code snippets for better understanding ?

**Comment by rumyantseva** [comment] 2023-05-16 07:46
@Aditya1404Sal sounds reasonable! Feel free to send a pull request draft if you want.

**Comment by Aditya1404Sal** [comment] 2023-05-18 19:28
@rumyantseva I've made the draft PR , Do let me know of my shortcomings.

**Closed** 2023-07-19 07:57 UTC
Labels: good first issue, code/chore
