### ISSUE TITLE
Using multiple dots in a row in path results in panic

### ISSUE THREAD

**Issue by noisersup** [FerretDB/FerretDB#1873] opened 2023-01-25 16:29 UTC
The solution here is really simple, but having in mind that we call `NewPathFromString` from many places and it doesn't return any error, will probably require a lot of refactoring in those places.

### Versions

main branch

### What did you do?

I did run incorrect query:

```
test> db.val.find({"v..":42})
```
Same issue occurs on:
```
test> db.val.find({".":42})
```
### What did you expect to see?

Some error related to invalid dot notation or usage of dots in key.

### What did you see instead?

```
MongoNetworkError: connection 3 to 172.17.0.1:27017 closed
```

```
2023-01-25T17:24:07.367+0100    WARN    // 172.19.0.4:48428 -> 172.17.0.1:27017         clientconn/conn.go:151  Failed to set deadline: set tcp 172.17.0.1:27017: use of closed network conn
ection
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func1
        github.com/FerretDB/FerretDB/internal/clientconn/conn.go:151
panic: path element must not be empty [recovered]
        panic: path element must not be empty
(err = <nil>)
```

**Comment by AlekSi** [comment] 2023-02-13 06:19
Duplicate of #1954.

**Closed by AlekSi** 2023-02-13 06:19 UTC
Labels: code/bug
